[package]
name = "rosey-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
rosey-core = { path = "../rosey-core" }
rosey-fs = { path = "../rosey-fs" }
rosey-metadata = { path = "../rosey-metadata" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
